# Generated by Django 2.2.8 on 2019-12-18 13:54

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='word',
            name='translations',
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name='translations'),
        ),
    ]
