# Generated by Django 2.2.8 on 2019-12-19 10:34

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='translations',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, db_index=True, default={}, null=True, verbose_name='translations'),
        ),
    ]
