# Generated by Django 2.1 on 2018-08-19 11:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='uploads', verbose_name='image')),
                ('remote_image', models.URLField(blank=True, null=True, verbose_name='remote image url')),
                ('word', models.CharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='word')),
                ('definition', models.TextField(db_index=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='definition')),
                ('examples', models.TextField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='definition')),
                ('translation', models.CharField(blank=True, db_index=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='translation')),
                ('pronunciation', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='pronunciation')),
                ('complete', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='complete')),
                ('priority', models.PositiveIntegerField(choices=[(0, 'very low'), (1, 'low'), (2, 'normal'), (3, 'high'), (4, 'very high')], db_index=True, default=2, verbose_name='priority')),
                ('last_showed_at', models.DateTimeField(blank=True, null=True, verbose_name='last showed at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_card_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='uploads', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='deck',
            name='remote_image',
            field=models.URLField(blank=True, null=True, verbose_name='remote image url'),
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.Deck', verbose_name='deck'),
        ),
        migrations.AddField(
            model_name='card',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_card_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
    ]
