# Generated by Django 2.1 on 2018-08-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20180819_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is default'),
        ),
    ]
