# Generated by Django 2.1 on 2018-08-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20180821_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('word',)},
        ),
    ]
