# Generated by Django 2.1 on 2018-08-22 13:15

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0006_auto_20180821_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_correct', models.BooleanField(db_index=True, verbose_name='is correct')),
                ('is_hint', models.BooleanField(db_index=True, default=False, verbose_name='is hint')),
                ('answer', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='word')),
                ('score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='score')),
                ('form', models.CharField(choices=[('listen', 'listen'), ('write', 'write'), ('choose', 'choose')], db_index=True, max_length=30, verbose_name='form')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AlterField(
            model_name='card',
            name='definition',
            field=ckeditor.fields.RichTextField(db_index=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='definition'),
        ),
        migrations.AlterField(
            model_name='card',
            name='examples',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='examples'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='cards.Card', verbose_name='card'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_attempt_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_attempt_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
    ]
