# Generated by Django 2.1 on 2018-08-22 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20180822_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='answer',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='answer'),
        ),
    ]
