# Generated by Django 2.1 on 2018-09-07 14:35

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20180822_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='antonyms',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='antonyms'),
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.CharField(choices=[('word', 'word'), ('phrase', 'phrase'), ('phrasal_verb', 'phrasal verb')], db_index=True, default='word', max_length=30, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='card',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='note'),
        ),
        migrations.AddField(
            model_name='card',
            name='synonyms',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='synonyms'),
        ),
        migrations.AddField(
            model_name='card',
            name='transcription',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='transcription'),
        ),
    ]
