# Generated by Django 2.1 on 2018-09-10 11:34

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20180907_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='antonyms',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='antonyms'),
        ),
        migrations.AlterField(
            model_name='card',
            name='synonyms',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='synonyms'),
        ),
    ]
