# Generated by Django 2.1 on 2018-10-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20180910_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='form',
            field=models.CharField(choices=[('listen', 'listen'), ('write', 'write'), ('choose', 'choose'), ('speak', 'speak')], db_index=True, max_length=30, verbose_name='form'),
        ),
    ]
