# Generated by Django 2.1 on 2018-10-03 09:02

import django.core.validators
from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20181001_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='antonyms',
            field=markdownx.models.MarkdownxField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='antonyms'),
        ),
        migrations.AlterField(
            model_name='card',
            name='definition',
            field=markdownx.models.MarkdownxField(db_index=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='definition'),
        ),
        migrations.AlterField(
            model_name='card',
            name='examples',
            field=markdownx.models.MarkdownxField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='examples'),
        ),
        migrations.AlterField(
            model_name='card',
            name='note',
            field=markdownx.models.MarkdownxField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='card',
            name='synonyms',
            field=markdownx.models.MarkdownxField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='synonyms'),
        ),
    ]
