# Generated by Django 2.1 on 2018-10-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_auto_20181003_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('word', 'deck')},
        ),
        migrations.AlterUniqueTogether(
            name='deck',
            unique_together=set(),
        ),
    ]
