# Generated by Django 2.1 on 2018-10-03 09:31

from django.db import migrations

from cards.models import Deck


def prepare(apps, schema_editor):
    if not Deck.objects.filter(pk=1).count():
        deck = Deck()
        deck.id = 1
        deck.title = 'main'
        deck.description = 'the default deck'
        deck.is_default = True
        deck.created_by_id = 1
        deck.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_auto_20181003_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('word', 'deck')},
        ),
        migrations.AlterUniqueTogether(
            name='deck',
            unique_together=set(),
        ),
        # migrations.RunPython(prepare),
    ]
