# Generated by Django 2.1 on 2018-10-03 09:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_auto_20181003_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.Deck', verbose_name='deck'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='definition',
            field=markdownx.models.MarkdownxField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='definition'),
        ),
    ]
