# Generated by Django 2.1 on 2018-10-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_auto_20181003_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ('order',)},
        ),
    ]
