# Generated by Django 2.1 on 2018-10-01 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nativecards', '0002_auto_20180824_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='cards_to_repeat',
            field=models.PositiveIntegerField(default=5, help_text='number of cards to repeat per the lesson', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='cards to repeat'),
        ),
    ]
