# Generated by Django 2.1 on 2018-10-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nativecards', '0003_auto_20181001_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='play_audio_on_open',
            field=models.BooleanField(db_index=True, default=True, help_text='whether to play an audio when opening the card?', verbose_name='play audio on open'),
        ),
    ]
