# Generated by Django 2.1 on 2018-10-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nativecards', '0004_settings_play_audio_on_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='play_audio_on_open',
            field=models.BooleanField(db_index=True, default=True, help_text='Play an audio when the card is opening', verbose_name='play audio on open'),
        ),
    ]
