# Generated by Django 2.2.7 on 2019-11-21 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nativecards', '0010_auto_20181025_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='cards_per_lesson',
            field=models.PositiveIntegerField(default=10, help_text='number of cards to study per the lesson', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='cards per lesson'),
        ),
    ]
