# Generated by Django 2.2.8 on 2019-12-16 12:20

from django.db import migrations
import nativecards.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nativecards', '0011_auto_20191121_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='language',
            field=nativecards.fields.LanguageField(blank=True, choices=[('en', 'English'), ('ru', 'Russian'), ('de', 'German'), ('fr', 'French'), ('tr', 'Turkish')], help_text='target language for translations', max_length=2, null=True, verbose_name='language'),
        ),
    ]
